pagopa/dx

- .github/workflows/infra_plan.yaml
- README.md
Import changes from [dx-typescript](https://github.com/pagopa/dx-typescript/pull/11) repo.
Add documentation in README.md to explain what the template does and how to use it.
A single template to perform a very common action as infra validation in PRs
> [DEVEX-108] Infrastructure CI workflow template

- .github/workflows/infra_plan.yaml
Update infra_plan.yaml workflow template by adding an optional parameter to override the path where execute the code review.
It was previously hardcoded to infra/resources, but that path is not applicable to few repositories such as `io-infra`. For this reason, this PR adds an optional parameter `base_path` to allow clients to set the path to the desired location
> [DEVEX-108] Add optional parameter to PR infra workflow

- .github/workflows/infra_apply.yaml
- README.md
Import changes from [dx-typescript](https://github.com/pagopa/dx-typescript/pull/14) repo.
Add documentation in README.md to explain what the template does and how to use it.
A single template to perform a very common action as infra deployment
> [DEVEX-109] Infrastructure CD workflow template

- .github/workflows/docker_image_build.yaml
Ref https://github.com/pagopa/dx-typescript/pull/16
> [DEVEX-38] Add workflow to build and publish Docker images

- .github/workflows/infra_apply.yaml
- .github/workflows/infra_plan.yaml
Applied best practices to protect workflows from malicious external inputs
Security
> [DEVEX-111] Secure workflows from external inputs

- .github/workflows/function_app_deploy.yaml
Add a workflow template to automate Function App deployments for Node workloads
Make easier the deployment of Function App
> [DEVEX-122] Add Function App deploy workflow template for Node workloads

- infra/modules/azure_function_app/outputs.tf
Set non-available outputs to null
Consumer can't understand if a value has been given or not. Setting them to null allows the consumer to perform this kind of checks
> [DEVEX-121] Update Function App module outputs

- .github/workflows/code-review.yaml
- .github/workflows/release.yaml
1. Add `corepack` to `release.yaml` workflow 
2. `code_review` now uses `js_code_review` from the same checkout
`release.yaml` workflow is broken https://github.com/pagopa/dx/actions/runs/9251808514
> Fix release workflow

- package.json
1. Add `build` script to the root workspace
this script enables us to build the entire monorepo before publishing
> Add "build" script

- .changeset/config.json
1. Set `public` as the default publishing mode to the NPM registry for changesets
With the previous `access` value, our packages will be published as `private` (requiring a NPM paying subscription, to publish to the private registry)
> Update changesets config

- packages/eslint-config/README.md
1. Remove eslint 9 references from README
Our configuration is compatible with eslint >= 8
> Remove ESLint 9 references from README

- .github/workflows/infra_plan.yaml
Update the `printf` expression to avoid any misleading format specifier
Avoid that percentage symbol could be interpreted by bash as a format specifier like `%s`, causing a script failure
> [DEVEX-132] Fix TF plan output in case of percentage symbol

- .github/workflows/function_app_deploy.yaml
Add support to deploy zip on the single slot
Not all Function App have a staging slot, this scenario should be supported
> [DEVEX-122] Update Function App workflow to support Function App with a single slot

- infra/modules/azure_function_app/locals.tf
The `-` character replace is performed for the entire string and not for the prefix only
If the `app_name` contains a `-`, it must be removed too
> [DEVEX-133] Fix the Storage Account name generation in Azure Functions App module

- decisions/0001-we-use-yarn-as-package-manager.md
- decisions/0002-we-use-turborepo-task-manager.md
- decisions/0003-we-use-a-single-monorepo-folder.md
- decisions/0004-we-use-folder-convention-for-infrastructure-resource-definitions.md
- decisions/0005-we-use-yarn-with-pnp.md
Moved ADRs from playground to dx.
Documentation belong to the dx repository.
> [DEVEX-136] Add ADRs

- infra/modules/azure_app_service/subnets.tf
- infra/modules/azure_function_app/subnets.tf
1. Enable `Microsoft.Web` endpoint to the subnet created by `function_app` e `app_service` modules
This change is mandatory to allow our web apps to communicate internally.
> Add Microsoft.Web service endpoint to web app modules subnets

- infra/modules/azure_federated_identity_with_github/README.md
- infra/modules/azure_federated_identity_with_github/main.tf
- infra/modules/github_selfhosted_runner_on_container_app_jobs/README.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/main.tf
Upgrade Terraform version constraints in `azure_federated_identity_with_github` and `github_selfhosted_runner_on_container_app_jobs` modules
Dependency doesn't have strictly requirements anymore, so it is possible to do the same here
> Upgrade Terraform version constraints

- decisions/.prettierrc
- decisions/0001-we-use-yarn-as-package-manager.md
- decisions/0002-we-use-turborepo-task-manager.md
- decisions/0003-we-use-a-single-monorepo-folder.md
- decisions/0004-we-use-folder-convention-for-infrastructure-resource-definitions.md
- decisions/0005-we-use-yarn-with-pnp.md
- decisions/0006-we-start-with-typescript-and-azure.md
Add adr about the choice of Typescript and Azure
as our first technology stack to work with.
I've wrapped all lines to 80 characters.
Users're gonna ask about this.
> [DEVEX-145] Add ADR about first technology stack

- infra/identity/dev/main.tf
- infra/identity/prod/main.tf
- infra/repository/data.tf
- infra/repository/github_branch_rules.tf
Created missing github environments
> [EC-281] Created github environments and fixed identity module

- infra/repository/github_repository.tf
> Fix repository homepage_url

- .github/workflows/infra_drift_detection.yml
Updated Drift Detection by removing unused variables and introducing a new step for Slack notification in case of each failure.
Removed webook_url input to avoid clear value in logs.
Changed Slack notification action with `slackapi` official.
We have added a notification step to receive alerts for issues beyond drift detection related to pipeline execution.
> [EC-350] Update Drift Detection workflow with Failure notification

- CODEOWNERS
Set `engineering-team-cloud-eng` codeowner of `infra` and `github` paths
> Set engineering-team-cloud-eng codeowner paths

- CODEOWNERS
> Set the correct path for engineering-team-cloud-eng in CODEOWNERS

- website/blog/001-devex-initiative.mdx
> [DEVEX-161] Small fixes to blog post

- website/blog/001-devex-initiative.mdx
- website/docusaurus.config.ts
> [DEVEX-161] Cosmetic fixes to blog post

- website/blog/001-devex-initiative.mdx
> Cosmetix fix to blog post

- website/docs/Docs/standards/azure-naming-convention.md
- website/docs/Docs/standards/index.md
Add doc for Azure naming convention
Official documentation after RFC
> Add doc for Azure naming convention

- website/docs/Docs/standards/infra-folder-structure.md
Add docs for infra folder structure, a new standard introduced some time ago.
This doc explains where and how to define Terraform configurations in a repository, including accessory configurations like the repository one.
> Add docs for infra folder structure

- website/docs/Docs/pipelines/drift-detection.md
- website/docs/Docs/pipelines/index.md
Add doc for Drift Detection Workflow
Official documentation after RFC
> Add doc for Drift Detection Workflow

- website/blog/001-devex-initiative.mdx
This pull request updates the links in the blog post "001-devex-initiative.mdx" to point to the correct locations on the website. The outdated links have been replaced with the new ones.
> [DEVEX-161] Update links to website

- .pre-commit-config.yaml
- .tflint.hcl
Added `tflint` into pre-commit
Added `.tflint.hcl` file for configuration
**TFLint** ensure consistent Terraform code quality and catch potential issues early. By automatically running **TFLint** before committing changes, we can enforce best practices, detect misconfigurations, and improve the overall reliability of our infrastructure code. This integration helps maintain clean, error-free code and reduces the risk of introducing bugs into production environments.
**Note**: TFLint must be installed locally on your machine for the pre-commit hook to function correctly. ([Installation guide](https://github.com/terraform-linters/tflint?tab=readme-ov-file#installation))
Useful links:
https://github.com/terraform-linters/tflint
https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov …
> [DEVEX-185] Added tflint into pre-config configuration

- website/docs/articles/azure-tracing.md
This pull request adds caching functionality to the AI example. Previously, the AI setup did not include caching, which could result in data loss on restarts.
> [DEVEX-161] Add cache to AI example

- website/docs/pipelines/triggers.md
Add guidelines to instruct developers on best practices about trigger pipelines, to maximize their usage and find optimal configurations.
> [DEVEX-105] Add guidelines for pipeline triggers

- website/docs/articles/azure-tracing.md
This pull request fixes the instrumentation for AI. 
The changes ensure that the AI SDK is properly set up and started, and that the native node fetch is instrumented correctly. 
Additionally, the pull request adds support for optional Azure Functions traces.
> docs: fix instrumentation for AI

- decisions/0008-we-use-changeset-for-releases.md
> Add Changesets ADR

- decisions/0007-we-use-pre-commit.md
> Add pre-commit ADR

- decisions/0009-we-use-eslint-for-liting.md
Introduce an architectural decision record (ADR) outlining the adoption of ESLint as the primary linting tool to enhance code quality and maintainability in the development workflow.
> Add ESLint decision record for linting

- .changeset/clever-pots-boil.md
- website/docs/articles/using-terraform-registry-modules.md
Document how to securely use terraform registry modules
> [CES-664] Document how to securely use terraform registry modules

- .changeset/sixty-moose-poke.md
- website/docs/infrastructure-as-code/using-terraform-registry-modules.md
> Added troubleshooting for sha256sum error and disable automatic pre-commits

- .changeset/curly-trees-share.md
> Fix azure_github_environment_bootstrap package name in changeset

- website/docs/index.md
Updated documentation index to remove warning about beta status of DX initiative.
> docs: refactor documentation for Developer Experience Initiative and update current status list

- website/docs/articles/azure-tracing.md
Revise the documentation to provide clearer guidance on using Application Insights.
> docs: update documentation for Application Insights

- website/docs/articles/azure-tracing.md
Enhance the Azure tracing documentation by improving clarity and consistency throughout the text, ensuring better understanding for users.
> Improve clarity and consistency in Azure tracing documentation

- yarn.lock
Removed wrong named package `azure_repo_starter_pack` from yarn lock 
This would cause [release pipelines to fail](https://github.com/pagopa/dx/actions/runs/13175836654/job/36774809952)
> Fix yarn lock removing unused package

- website/docs/infrastructure/archive-data.md
> Add documentation on how to securely archive data of a dismissed project

- .changeset/gentle-bananas-shop.md
- infra/modules/azure_github_environment_bootstrap/github_repository.tf
- infra/repository/github_repository.tf
Use Pull Request description as commit description when squashing
Closes #CES-778
> Set PR_BODY as commit message when squashing

- .github/PULL_REQUEST_TEMPLATE.md
- website/docs/articles/azure-tracing.md
Corrected typos and enhanced the clarity of the Azure tracing documentation to improve readability and understanding.
> Fix typos and improve clarity in Azure tracing documentation

- website/docs/infrastructure/azure-policy/index.md
- website/docs/infrastructure/azure-policy/policy-catalog/index.md
- website/docs/infrastructure/azure-policy/policy-catalog/specific-tags.md
Added new pages for Azure Policies
To increment documentation of dx resources
Resolves: #CES-756
> [CES-756] Add Azure Policy documentation into dx website

- .changeset/smart-chicken-turn.md
- infra/modules/azure_github_environment_bootstrap/README.md
- infra/modules/azure_github_environment_bootstrap/ad_admin_iam.tf
- infra/modules/azure_github_environment_bootstrap/ad_devs_iam.tf
- infra/modules/azure_github_environment_bootstrap/ad_ext_iam.tf
- infra/modules/azure_github_environment_bootstrap/id_app_iam.tf
- infra/modules/azure_github_environment_bootstrap/id_infra_cd_iam.tf
- infra/modules/azure_github_environment_bootstrap/id_infra_ci_iam.tf
- infra/modules/azure_github_environment_bootstrap/locals.tf
- infra/modules/azure_github_environment_bootstrap/main.tf
- infra/modules/azure_github_environment_bootstrap/outputs.tf
- infra/modules/azure_github_environment_bootstrap/tests/mono_repo.tftest.hcl
- infra/modules/azure_github_environment_bootstrap/variables.tf
Add an optional variable to accept a list of resource group to apply IAM roles to
Teams may have multiple resource groups under their ownership, and applying IAM roles over and over again on each of them is a slow task
> [CES-774] Update bootstrap module to accept a list of resource group ids

- website/docs/infrastructure/azure-iam.md
Add documentation to explain how and why IAM DX framework was designed
Making everyone understands how the framework was designed and how to exploit it
> [CES-775] Add documentation for IAM framework

- website/docs/infrastructure/azure-iam.md
Update the Azure IAM documentation to enhance clarity.
> Revise Azure IAM documentation for clarity and management guidelines

- website/docs/infrastructure/azure-iam.md
Corrected typographical errors and updated module versioning in the Azure IAM documentation for clarity and accuracy.
> Fix typos and update module versioning in Azure IAM documentation

- website/docs/articles/azure-tracing.md
- website/docs/infrastructure/appservice-hidden-appsettings.md
- website/docs/infrastructure/appservice-plan-dns-resolution.md
- website/docs/infrastructure/archive-data.md
- website/docs/infrastructure/azure-policy/index.md
- website/docs/infrastructure/azure-policy/policy-catalog/specific-tags.md
- website/docs/infrastructure/iam-cross-subscription.md
- website/docs/pipelines/azure-login.md
- website/docs/pipelines/drift-detection.md
- website/docs/pipelines/triggers.md
Update sidebar labels throughout the documentation to enhance clarity and maintain consistency in terminology.
> Revise sidebar labels for clarity and consistency across documentation

- .changeset/gorgeous-points-train.md
- website/docusaurus.config.ts
The sidebar already looks crammed with tens of links making navigation harder
> Make sidebar collapsible to make navigation easier

- .github/actions/push-module/action.yaml
- .github/workflows/push_modules_to_subrepo.yml
- infra/scripts/add-module.sh
> Use the new pagopa-dx GitHub organization to host dx tf modules

- .changeset/wild-moons-collect.md
Bump module version as #314 added some documentation without changeset
Close #CES-775
> Bump azure_github_environment_bootstrap version

- website/docs/conventions/git/branch-name.md
- website/docs/conventions/git/commit-message.md
Enhance branch naming conventions for clarity and context.
> Enhance Git conventions

- .changeset/silent-forks-hammer.md
- infra/modules/azure_container_app/README.md
- infra/modules/azure_container_app_environment/README.md
Update documentation for Container App and Container App Environment terraform modules based on new guide lines.
Resolves: CES-869
> Update `Container App` and `Container App Environment` documentation

- apps/website/docs/articles/azure-github-environment-bootstrap.md
- apps/website/docs/infrastructure/azure/azure-iam.md
- apps/website/docs/infrastructure/azure/iam-cross-subscription.md
- infra/modules/azure_core_infra/README.md
- infra/modules/azure_core_infra/example/develop/README.md
- infra/modules/azure_cosmos_account/README.md
Revise module source paths to align with the new naming convention across various documentation files.
> Update documentation to reflect new organization on Terrafom registry

- .changeset/strong-kings-kiss.md
- infra/modules/azure_cosmos_account/README.md
Update documentation for Cosmos Account terraform module based on new guide lines.
Resolves: CES-871
> Update `Cosmos Account` module documentation

- .changeset/pink-tools-fly.md
- infra/modules/azure_core_infra/README.md
Update documentation for `Core Infra` terraform module based on new guide lines.
Resolves: CES-870
> Update `Core Infra` module documentation

- apps/website/blog/002-azure-github-environment-bootstrap.mdx
- apps/website/docs/infrastructure/azure/azure-iam.md
- apps/website/docusaurus.config.ts
> Move Bootstrap module announcement to blog

- apps/website/blog/002-benchmark-openapi-gen.mdx
- apps/website/blog/003-azure-github-environment-bootstrap.mdx
> Move "Benchmark for Typescript Code Generators from OpenAPI" article to blog

- .changeset/hip-poets-study.md
- infra/provider/README.md
- infra/provider/docs/functions/resource_name.md
- infra/provider/internal/provider/function_resource_name.go
Fix the storage account naming convention and add CMK storage account resource type
> Update Provider with new resource and fixed storage account

- .changeset/cuddly-bobcats-doubt.md
- infra/modules/github_environment_bootstrap/README.md
- infra/modules/github_environment_bootstrap/github_branch_rules.tf
- infra/modules/github_environment_bootstrap/github_repository.tf
- infra/modules/github_environment_bootstrap/main.tf
- infra/modules/github_environment_bootstrap/package.json
- infra/modules/github_environment_bootstrap/tests/mono_repo.tftest.hcl
- infra/modules/github_environment_bootstrap/variables.tf
- yarn.lock
Based on [RFC-028](https://pagopa.atlassian.net/wiki/spaces/DevEx/pages/1621950630/RFC-DX-028+Configure+cloud+agnostic+repositories)
Closes CES-924
> Copy GH repository configuration in new module github_environment_bootstrap

- .changeset/shy-carrots-eat.md
- infra/provider/README.md
- infra/provider/docs/functions/resource_name.md
- infra/provider/docs/index.md
- infra/provider/internal/provider/function_resource_name.go
- infra/provider/internal/provider/provider.go
Improve the pagopa-dx/azure provider with italynorth and westeurope values support for location parameter used by resource_name function
> Improve azure provider with location full name support

- .changeset/odd-onions-act.md
- infra/modules/azure_storage_account/README.md
- infra/modules/azure_storage_account/examples/complete/README.md
- infra/modules/azure_storage_account/examples/complete/locals.tf
- infra/modules/azure_storage_account/examples/complete/main.tf
- infra/modules/azure_storage_account/examples/complete/versions.tf
- infra/modules/azure_storage_account/locals.tf
- infra/modules/azure_storage_account/main.tf
- infra/modules/azure_storage_account/tests/setup/README.md
- infra/modules/azure_storage_account/tests/setup/main.tf
- infra/modules/azure_storage_account/tests/setup/variables.tf
Update storage_account module with new dx provider version
> Update provider version in storage account module for null domain support

- .changeset/loud-rice-return.md
- infra/provider/README.md
- infra/provider/docs/functions/resource_name.md
- infra/provider/internal/provider/function_resource_name.go
Add managed_identity type support inside resource_name provider function
> Update resource_name provider function with managed_identity type

- .changeset/orange-shoes-compare.md
- apps/website/docs/infrastructure/using-terraform-registry-provider.md
Add documentation for terraform provider
Resolves: CES-895
> Add Terraform Provider documentation page

- .changeset/healthy-garlics-lick.md
- infra/github-runner/dev/tfmodules.lock.json
- infra/modules/github_selfhosted_runner_on_container_app_jobs/README.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/README.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/basic/README.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/basic/data.tf
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/basic/locals.tf
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/basic/main.tf
- infra/modules/github_selfhosted_runner_on_container_app_jobs/examples/basic/versions.tf
> Add documentation for GitHub SelfHosted Runner On Container App Jobs

- .vscode/settings.json
- .yarn/sdks/prettier/bin/prettier.cjs
- .yarn/sdks/typescript/bin/tsc
- .yarn/sdks/typescript/bin/tsserver
- .yarn/sdks/typescript/lib/tsc.js
- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/sdks/typescript/lib/tsserverlibrary.js
- .yarn/sdks/typescript/lib/typescript.js
- .yarn/sdks/typescript/package.json
- apps/website/turbo.json
- package.json
- yarn.lock
Also, fix the `docs` workspace configuration to enable type checking and caching.
> Update root workspace deps

- .changeset/lemon-radios-knock.md
- infra/modules/azure_event_hub/locals.tf
> Fix eventhub name

- apps/website/docs/getting-started.md
- apps/website/docs/infrastructure/monorepository-setup.md
Enhance the clarity and consistency of documentation, ensuring better understanding and usability for users.
> Improve documentation clarity and consistency

- .changeset/green-lions-reply.md
- infra/modules/azure_cdn/README.md
Update CDN module documentation following guidelines
Resolves: CES-868
> Update Documentation for CDN module

- .changeset/bright-toes-hug.md
- infra/modules/azure_github_environment_bootstrap/README.md
- infra/modules/azure_github_environment_bootstrap/id_infra_cd_iam.tf
- infra/modules/azure_github_environment_bootstrap/id_infra_ci_iam.tf
- infra/modules/azure_github_environment_bootstrap/tests/mono_repo.tftest.hcl
> Add roles to manage Container Apps via GitHub workflows

- apps/website/docs/articles/azure-tracing.md
- apps/website/docs/articles/setting-up-devcontainer.md
- apps/website/docs/conventions/azure-naming-convention.md
- apps/website/docs/conventions/git/branch-name.md
- apps/website/docs/conventions/pull-requests/auto-merge.md
- apps/website/docs/conventions/pull-requests/changeset.md
- apps/website/docs/conventions/pull-requests/code-review/conventional-comments.md
- apps/website/docs/conventions/pull-requests/code-review/index.md
- apps/website/docs/index.md
Correct various typos and improve formatting across multiple documentation files to enhance clarity and consistency.
> Fix typos and formatting in documentation

- apps/website/docs/infrastructure/monorepository-setup.md
- apps/website/docs/infrastructure/using-terraform-registry-modules.md
- apps/website/docs/infrastructure/using-terraform-registry-provider.md
Revise the documentation for setting up a new mono-repository, enhancing clarity on GitHub authentication methods for Terraform operations.
> Update bootstrapping instructions for new projects

- apps/website/docs/infrastructure/azure/index.md
- apps/website/docs/infrastructure/contributing-to-dx-terraform-modules/index.md
Adjust the sidebar positions for the Azure and Terraform documentation to improve navigation.
> Update sidebar positions for Azure and Terraform Modules

- .changeset/sharp-comics-whisper.md
- apps/website/package.json
- apps/website/src/pages/index.tsx
- yarn.lock
The build failed due to different versions of docusaurus dependencies. Now the dependencies version are aligned
> Upgrade docusaurus dependencies

- .changeset/pink-crabs-press.md
- infra/modules/azure_container_app_environment/id.tf
- infra/modules/azure_container_app_environment/tests/containerappenv.tftest.hcl
> Fix (again) name of the user-assigned managed identity of Container App Environment

- .changeset/open-mammals-post.md
- infra/modules/azure_container_app_environment/README.md
- infra/modules/azure_container_app_environment/outputs.tf
> Container App Environment module exports all details of the user-assigned managed identity

- .changeset/spicy-deer-worry.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/locals.tf
> Remove trailing hyphens from Container App Job name

- .changeset/five-trees-open.md
- infra/modules/github_selfhosted_runner_on_container_app_jobs/locals.tf
> Improve code to remove trailing hyphens from Container App Job name

- .github/actions/docker-build-push/action.yaml
> Add action to encapsulate Docker Build and Push

- apps/website/docs/articles/azure-tracing.md
Closes CES-946 depends on #439
> Add information about '@pagopa/azure-tracing' package

- .changeset/two-dragons-fry.md
- packages/azure-tracing/package.json
- yarn.lock
This fixes the issue explained in https://github.com/microsoft/ApplicationInsights-node.js/issues/1423
> Upgrade OpenTelemetry dependencies

- .changeset/funny-buttons-start.md
- apps/website/docs/pipelines/static-analysis.md
> Add static analysis documentation

- apps/website/docusaurus.config.ts
- apps/website/package.json
- yarn.lock
This PR implements a local search feature for our Docusaurus documentation site using the `@easyops-cn/docusaurus-search-local` plugin.
**Changes made:**
- Added `@easyops-cn/docusaurus-search-local`, `@docusaurus/theme-common` and `@docusaurus/plugin-content-docs` packages
- Configured the search plugin in `docusaurus.config.ts`
**Testing:**
- yarn build
- yarn start serve
**Demo:**
Resolves: CES-948
> Add local search functionality to Docusaurus website

- .github/actions/download-artifact/action.yaml
- .github/actions/upload-artifact/action.yaml
A vulnerability was found, an update is compelling
Close CES-975
> Update upload/download artifact actions

- .github/workflows/_cron-terraform-drift-detection.yaml
- .github/workflows/_release-bash-modules-to-subrepo.yaml
- .github/workflows/_release-bash-provider-to-subrepo.yaml
- .github/workflows/_release-changesets-pull-request.yaml
- .github/workflows/_release-docusaurus-docs-website.yaml
- .github/workflows/_validate-docker-devcontainer.yaml
- .github/workflows/_validate-docusaurus-docs-website.yaml
- .github/workflows/_validate-go-test-provider.yaml
- .github/workflows/_validate-terraform-static-analysis.yaml
- .github/workflows/_validate-terraform-test-modules.yaml
- .github/workflows/_validate-typescript-code-review.yaml
- .github/workflows/static_analysis.yaml
> Set permissions on GitHub internal workflow jobs

- .github/workflows/_release-changesets-pull-request.yaml
> Set write permissions to changeset release workflow

- apps/website/docs/pipelines/node-webapp-deploy.md
> Add documentation for the deployment of Node.js Web Apps

- .github/workflows/_cron-terraform-drift-detection.yaml
> Fix drift detection workflow

- apps/website/docs/pipelines/docker-image-build.md
> Document Docker Image Build pipeline

- apps/website/docs/pipelines/node-function-app-deploy.md
> Add documentation for the deployment of Node.js Function Apps

- .changeset/red-tires-beam.md
- infra/provider/internal/provider/function_resource_name.go
> Add support to DX Terraform Provider to generate names for Service Bus

- .changeset/yummy-states-sleep.md
- infra/modules/azure_app_service/app_service.tf
- infra/modules/azure_app_service/app_service_slot.tf
- infra/modules/azure_app_service/tests/appservice.tftest.hcl
- infra/modules/azure_app_service_exposed/app_service.tf
- infra/modules/azure_app_service_exposed/app_service_slot.tf
- infra/modules/azure_app_service_exposed/tests/appservice.tftest.hcl
> Revert "TLS 1.3 Upgrade for Azure App Services modules"

- .changeset/crazy-tigers-stand.md
- infra/modules/azure_function_app/function_app.tf
- infra/modules/azure_function_app/function_app_slot.tf
- infra/modules/azure_function_app/tests/functionapp.tftest.hcl
- infra/modules/azure_function_app_exposed/function_app.tf
- infra/modules/azure_function_app_exposed/function_app_slot.tf
- infra/modules/azure_function_app_exposed/tests/functionapp.tftest.hcl
> Revert "TLS 1.3 Upgrade for Azure Function Apps modules"

- .changeset/five-results-doubt.md
- apps/website/blog/005-azure-servicebus-namespace.mdx
- apps/website/docs/infrastructure/azure/using-service-bus.md
- infra/modules/azure_role_assignments/tests/role.tftest.hcl
- infra/modules/azure_service_bus_namespace/README.md
- infra/modules/azure_service_bus_namespace/package.json
> Add documentation and blog post for Service Bus

- .changeset/major-weeks-type.md
- infra/modules/azure_api_management/network.tf
> Fix rule declaration of APIM's Network Security Group

- .changeset/sad-singers-peel.md
- infra/modules/azure_github_environment_bootstrap/README.md
> Add examples about setup customization in Azure Bootstrapper module

- apps/website/docs/pipelines/drift-detection.md
> Improve Terraform Drift Detection workflow template documentation

- infra/resources/dev/.terraform.lock.hcl
- infra/resources/dev/README.md
Fix the identified drift in https://github.com/pagopa/dx/actions/runs/15387167252/job/43288150617
> Fix drift detection

- .github/actions/node-setup/action.yaml
- .github/workflows/function_app_deploy.yaml
Refactor the `function_app_deploy` workflow to avoid code duplication
Closes CES-1065
> Use node-setup action in function app deploy workflow

- .changeset/thin-pigs-sniff.md
- infra/modules/github_environment_bootstrap/README.md
- infra/modules/github_environment_bootstrap/workflow_permissions.tf
> Add packages write permissions to GitHub workflow

- .github/workflows/infra_plan.yaml
> Fix infra_plan failing when plan has no changes

- apps/website/docs/dev-containers/setting-up-devcontainer.md
This PR fixes the formatting issues in the devcontainer documentation article, particularly around tip boxes and spacing.
> Fix devcontainer article formatting

- .github/workflows/_release-changesets-pull-request.yaml
> Generate provenance attestation when publishing npm packages

- .changeset/bright-ducks-beg.md
- packages/azure-tracing/README.md
Clarify the usage of the provided functions.
> Improve README

- .changeset/warm-spoons-hang.md
- packages/azure-tracing/package.json
- packages/eslint-config/package.json
The repository URL is used to verify provenance attestation
> Add repository information in packages

- .changeset/ripe-pots-cheat.md
- infra/provider/README.md
- infra/provider/internal/provider/function_resource_name.go
> Add naming convention support for alerts over Service Bus entities

- .changeset/breezy-spiders-enter.md
- apps/website/blog/006-azure-servicebus-alerts.mdx
- infra/modules/azure_service_bus_alerts/README.md
- infra/modules/azure_service_bus_alerts/outputs.tf
Close [CES-1043](https://pagopa.atlassian.net/browse/CES-1043)
[CES-1043]: https://pagopa.atlassian.net/browse/CES-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add blog post for new Service Bus Alerts module

- apps/website/docs/infrastructure/azure/using-service-bus.md
> Add link to naming convention in Service Bus documentation

- .changeset/whole-buttons-yawn.md
- infra/modules/azure_common_values_exporter/package.json
- infra/modules/azure_core_infra/README.md
- infra/modules/azure_core_infra/main.tf
- infra/modules/azure_core_infra/outputs.tf
- infra/modules/azure_core_values_exporter/README.md
- infra/modules/azure_core_values_exporter/data.tf
- infra/modules/azure_core_values_exporter/main.tf
- infra/modules/azure_core_values_exporter/outputs.tf
- infra/modules/azure_core_values_exporter/package.json
- infra/modules/azure_core_values_exporter/variables.tf
- yarn.lock
Create a generic module that allows to read core values from azure-core-infra via terraform remote state as described in RFC-044
Blocks #594
> Implement module to extrapolate common values from core infra

- .changeset/tired-radios-warn.md
- apps/cli/src/adapters/commander/commands/doctor.ts
- apps/cli/src/adapters/node/repository.ts
- apps/cli/src/domain/__tests__/repository.test.ts
- apps/cli/src/domain/repository.ts
Verify `pre-commit` to be configured.
Closes CES-1096
> Verify `pre-commit` configuration using `doctor` command

- pnpm-workspace.yaml
This installs every dependency in the catalog
Start simple, and manually decide whether a dependency should be in the catalog or not.
> Remove catalogMode option

- .changeset/thick-mammals-dress.md
- infra/bootstrapper/_modules/bootstrapper/tfmodules.lock.json
- infra/bootstrapper/dev/tfmodules.lock.json
- infra/bootstrapper/prod/tfmodules.lock.json
- infra/core/dev/tfmodules.lock.json
- infra/core/prod/tfmodules.lock.json
- infra/modules/azure_function_app/README.md
- infra/modules/azure_function_app/locals.tf
- infra/modules/azure_function_app/main.tf
> Update Private Endpoint names in Function App module

- .changeset/eighty-deer-do.md
- infra/modules/azure_service_bus_alerts/active.tf
- infra/modules/azure_service_bus_alerts/tests/alerts.tftest.hcl
> Fix metric name in SBNS active message alert

- .github/instructions/copilot-instructions.md
Instruct Copilot agent within the context of this repository
> Add Copilot instructions

- .changeset/sour-spies-mate.md
- apps/cli/eslint.config.js
- apps/cli/src/adapters/commander/commands/info.ts
- apps/cli/src/adapters/commander/index.ts
- apps/cli/src/adapters/node/repository.ts
- apps/cli/src/config.ts
- apps/cli/src/domain/__tests__/data.ts
- apps/cli/src/domain/__tests__/info.test.ts
- apps/cli/src/domain/dependencies.ts
- apps/cli/src/domain/doctor.ts
- apps/cli/src/domain/info.ts
- apps/cli/src/domain/package-json.ts
- apps/cli/src/domain/repository.ts
- apps/cli/src/domain/validation.ts
- apps/cli/src/index.ts
Create the `info` command and show the `packageManager` used in the project
Closes CES-1150
> Show packageManager in `info` command

- .changeset/brown-kiwis-repair.md
- apps/cli/src/domain/info.ts
> Simplify detectPackageManager function readability

- .changeset/petite-hotels-attack.md
- apps/cli/src/adapters/node/repository.ts
- apps/cli/src/domain/__tests__/package-json.test.ts
- apps/cli/src/domain/__tests__/repository.test.ts
- apps/cli/src/domain/doctor.ts
- apps/cli/src/domain/package-json.ts
- apps/cli/src/domain/repository.ts
After the code introduced in #756, we can cleanup some code.
Closes CES-1164
> Refactor removing redundant functions

- .github/actions/cdn-code-deploy/action.yaml
- .github/actions/docker-build-push/action.yaml
- .github/actions/download-artifact/action.yaml
- .github/actions/get-all-resources/action.yaml
- .github/actions/get-modified-resources/action.yaml
- .github/actions/get-terraform-version/action.yaml
- .github/actions/keep-alive/action.yaml
- .github/actions/slack-notification/action.yaml
- .github/actions/terraform-setup/action.yaml
- .github/actions/upload-artifact/action.yaml
`action.yaml`, [according to its JSON Schema](https://www.schemastore.org/github-action.json) does not accept the `type` property as inputs are always `string`. Default values also need to be defined as `string` so `"true"` instead of `true`.
> Fix action.yaml files

- CONTRIBUTING.md
> Fix CONTRIBUTING file

- .changeset/eighty-dogs-bake.md
- apps/cli/src/domain/__tests__/info.test.ts
- apps/cli/src/domain/info.ts
> Trim `node` version

- .github/workflows/infra_apply.yaml
- .github/workflows/infra_plan.yaml
> Decrease Terraform lock timeout

- .devcontainer/features/shellcheck/README.md
- .devcontainer/features/shellcheck/devcontainer-feature.json
- .devcontainer/features/shellcheck/install.sh
[ShellCheck](https://github.com/koalaman/shellcheck?tab=readme-ov-file#shellcheck---a-shell-script-static-analysis-tool) is a linter for shell scripts
> Add ShellCheck feature

- .github/workflows/infra_plan.yaml
Close CES-1175
- No Cache: [4m 47s](https://github.com/pagopa/io-auth-n-identity-domain/actions/runs/16748351682/job/47417833295)
- Cache: [54s](https://github.com/pagopa/io-auth-n-identity-domain/actions/runs/16748351682)
> Disable Terraform state refresh in runs within 10 minutes

- .github/workflows/infra_plan.yaml
> Disable Terraform state file lock when planning in PR

- .changeset/rich-falcons-act.md
- infra/modules/azure_function_app/locals.tf
> Fix typo in Function App alert name

- .changeset/late-nails-cough.md
- infra/modules/azure_function_app/README.md
- infra/modules/azure_function_app/alerts.tf
- infra/modules/azure_function_app/tests/functionapp.tftest.hcl
- infra/modules/azure_function_app/tests/setup/README.md
- infra/modules/azure_function_app/tests/setup/main.tf
- infra/modules/azure_function_app/variables.tf
> Add support for multiple action groups to Function App module

- .changeset/brave-loops-post.md
- packages/monorepo-generator/templates/monorepo/.editorconfig
Add the option in the template file.
Related to https://github.com/pagopa/dx/pull/824#discussion_r2315291038
Closes CES-1237
> Add `trim_trailing_whitespace` option to editorconfig

- .pre-commit-config.yaml
> Set trivy parallelism to 1 to solve race conditions in CI

- .changeset/plain-hairs-try.md
- providers/azure/README.md
- providers/azure/docs/functions/resource_name.md
- providers/azure/internal/provider/function_resource_name.go
> Add APIM private endpoint naming for function

- .changeset/funny-ravens-itch.md
- infra/core/dev/moved.tf
- infra/core/prod/moved.tf
- infra/modules/azure_core_infra/locals.tf
> Add DNS zone for API Management in Azure Core Infra

- .changeset/slimy-roses-tickle.md
- infra/modules/azure_cdn/tests/setup/README.md
- infra/modules/azure_cdn/tests/setup/main.tf
After Storage Account module update CDN terraform test stop working correctly
Resolves: CES-1302
> Update Azure CDN module test

- .changeset/cold-melon-game.md
- .changeset/warm-peaches-play.md
- infra/modules/azure_core_infra/README.md
- infra/modules/azure_core_infra/outputs.tf
- infra/modules/azure_core_values_exporter/README.md
- infra/modules/azure_core_values_exporter/outputs.tf
These two new outputs reduce the DX cli need to generate additional data sources
Resolves CES-1331
> Output subscription and tenant id in core

- .changeset/stupid-emus-stop.md
- .github/workflows/_validate-typescript-code-review.yaml
- .github/workflows/js_code_review.yaml
- actions/detect-node-package-manager/action.yml
- apps/cli/src/adapters/codemods/update-code-review.ts
- apps/cli/src/adapters/codemods/use-azure-appsvc.ts
- apps/cli/src/adapters/codemods/use-pnpm.ts
- apps/cli/src/adapters/codemods/yaml.ts
Added warning notices in `node-setup` and PR comment on `js_code_review`
Closes CES-1159
> Add yarn deprecation notice

- .devcontainer/devcontainer.json
- .prettierignore
- apps/website/.prettierignore
- apps/website/blog/007-migrating-to-pnpm.mdx
Blog post in draft status (visible only on development) because we want to make it visible on `Oct 3, 2025`.
Closes CES-1161
> Add PNPM announcement blog post

- .changeset/new-chicken-bet.md
- apps/website/blog/001-assets/_apim-after.mdx
- apps/website/blog/001-assets/_apim-before.mdx
- apps/website/blog/001-assets/_autoscaling-after.mdx
- apps/website/blog/001-assets/_autoscaling-before.mdx
- apps/website/blog/001-assets/_deploy-after.mdx
- apps/website/blog/001-assets/_deploy-before.mdx
- apps/website/blog/001-assets/_terraform-apply-after.mdx
- apps/website/blog/001-assets/_terraform-apply-before.mdx
- apps/website/blog/001-devex-initiative.mdx
Enhance blog content by adding detailed examples for deploying Azure resources using Terraform and Azure DevOps workflows. This includes autoscaling configurations and API management setups.
> Refactor blog content for Azure DevOps and Terraform integration
