README.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/README.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/data.tf, infra/modules/github_selfhosted_runner_on_container_app_jobs/main.tf, infra/modules/github_selfhosted_runner_on_container_app_jobs/outputs.tf, infra/modules/github_selfhosted_runner_on_container_app_jobs/variables.tf
This code wraps the existing module to deploy a Container App job on an existing CAE, to use as GitHub self hosted runner.
Useful when a GitHub Actions must run in a VNET
=> [DEVEX-110] Add Terraform module to deploy GitHub self hosted runners

infra/modules/github_selfhosted_runner_on_container_app_jobs/README.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/main.tf, infra/modules/github_selfhosted_runner_on_container_app_jobs/variables.tf
Truncate container app job name after 20 characters and add a variable to override it if the generated value is not ok
If the repository name is too long, the module fails to apply because of max length in container app job name.
=> [DEVEX-110] Manage names too long in GitHub self-hosted runner module

.github/workflows/js_code_review.yaml
1. Add a new github reusable workflow: `js_code_review` that runs the `code-review` script in javascript monorepo. This workflow is configured to cache `turbo` output and sends (only when is enabled) test coverage reports to https://about.codecov.io/
Create a file named `code-review.yaml` in `.github/workflows` with the following content
```yaml
name: Code Review
on:
workflow_dispatch:
pull_request:
types: [opened, synchronize]
paths:
- apps/**
- packages/**
jobs:
js_code_review:
uses: pagopa/dx/.github/workflows/js_code_review.yaml@c461016f071d813b2012c88674df41c753f56b16
name: Code Review
secrets: inherit
```
=> [DEVEX-117] Add js_code_review reusable workflow

.github/workflows/infra_apply.yaml, .github/workflows/infra_plan.yaml
Remove `region` input parameter
A Terraform config might have more than one region. We took the decision to remove the region from folder hierarchy for this reason then
=> [DEVEX-41] Remove region from input parameters in infra workflows

.changeset/chilled-trains-occur.md, packages/eslint-config/index.js
1. Fix `eslint-vitest-plugin` configuration
2. Now `eslint` will ignore by default `generated` files
The current configuration is not working as expected
=> Fix @pagopa/eslint-config vitest rules

infra/modules/azure_app_service/README.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_plan.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service/data.tf, infra/modules/azure_app_service/locals.tf, infra/modules/azure_app_service/main.tf, infra/modules/azure_app_service/networking.tf, infra/modules/azure_app_service/outputs.tf, infra/modules/azure_app_service/subnets.tf, infra/modules/azure_app_service/variables.tf
A new module to create an Azure App Service.
This module creates:
subnet for the app service
production slot
staging slot
private endpoints
This module DOES NOT use vnet routing rules, but instead uses private endpoints to regulate app service access. Then, access is disabled from outside the vnet (without the vpn).
Naming convention is also forced.
Actual module is too complex and does not force to use certain patterns like private endpoints
=> [DEVEX-131] New TF module to create an Azure App Service

.github/workflows/docs_website_publish.yaml
This pull request fixes the workflow for GitHub Pages deployment. The path for uploading the build artifact has been updated to "./website/build".
=> fix: GitHub Pages deployment workflow

infra/modules/azure_function_app/function_app_slot.tf
Changed the name of the function app slot resource from the complete one to "staging".
The name of the staging slot is automatically concatenated with the name of the function app itself.
For this reason, the resulting name is extremely long and redundant.
Example:
This would become:
io-p-itn-svc-app-be-func-01-staging
=> Reduce function app slot name to staging

infra/modules/azure_function_app/README.md, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app/locals.tf
Set the AzureFunctionsWebHost__hostid environment variable on function app and its slot when the function name is longer than 32 characters
In the newly implemented trial-system project, an issue has been encountered. The name of the staging slot (that is the concatenation of the function app name and "staging") was longer than 32 characters.
The default host id (used to create a container in the function's storage account), equals to the complete name truncated to 32 characters. When the complete slot name is longer than 32 characters, the host id (aka container name) may collide with the one used by the function app and cause problems.
For this reason, in this PR, we are going to set the host id statically to avoid collisions. "production" for the function app and the slot name for the …
=> Fix function app slot host id collision

infra/modules/azure_app_service/README.md, infra/modules/azure_app_service/locals.tf, infra/modules/azure_app_service/subnets.tf, infra/modules/azure_app_service/variables.tf, infra/modules/azure_function_app/README.md, infra/modules/azure_function_app/locals.tf, infra/modules/azure_function_app/subnets.tf, infra/modules/azure_function_app/variables.tf
Add support for service endpoint configuration in subnet created by modules
Service endpoints needs to communicate with resources which don't have a private endpoint. Actually lot of resources don't have them, so this requirement is still valid
=> [DEVEX-153] Add support for subnet service endpoints in compute modules

website/docs/conventions/npm-scripts.md
This pull request adds documentation for naming conventions and guidelines for npm scripts. The documentation provides context, examples of script naming, and guidelines for writing npm scripts. It emphasizes self-contained commands, simplicity, atomicity, and avoiding lifecycle hooks. The documentation also suggests limiting the usage of `npm-run-all` and using tools like `turborepo` for advanced task coordination.
=> [DEVEX-161] Add npm scripts documentation

website/blog/001-devex-initiative.mdx, website/docs/articles/benchmark-openapi-gen.md
This pull request adds a new article titled "Benchmark for Typescript Code Generators from OpenAPI". The article provides an evaluation and comparison of various TypeScript OpenAPI generators for both frontend and backend development. It discusses the main requirements, additional features, and exclusion criteria for the generators. It also highlights the issues with the "openapi-zod-client" and "swagger-typescript-api + ts-to-zod" generators. The article concludes that as of June 2024, no OpenAPI generator fully meets the guiding principles, but it is appropriate to invest in the development of a Typescript code generator from OpenAPI that performs correct and complete runtime checks.
=> [DEVEX-161] Add article about OpenAPI client generation

infra/repository/github_repository.tf
Once a branch is merged in `main`, that branch should be safely deleted
Closes #CES-780
=> Enable branch deletion after PR merge

.github/PULL_REQUEST_TEMPLATE.md
Remove the pull request template to streamline contribution guidelines and enhance clarity for contributors.
=> Remove pull request template for clarity and efficiency

.changeset/chatty-lobsters-arrive.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service_exposed/app_service.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app_exposed/function_app.tf, infra/modules/azure_function_app_exposed/function_app_slot.tf
Set `var.health_check_path` as custom warm-up path to constraint the swap operation only when the source slots is healthy.
=> Set up custom warm-up in webapps modules

.changeset/few-singers-know.md, infra/modules/azure_api_management/monitor.tf, infra/modules/azure_api_management/tests/apim.tftest.hcl
When tier is set to `s`, but AI is enabled, the plan fails because it assumes the APIM logger exists.
With this change, when AI is enabled, then the module creates an APIM logger as well
Closes #273 #CES-799
=> Create APIM logger when AI is enabled

.changeset/ninety-mangos-drum.md, infra/modules/azure_api_management/README.md, infra/modules/azure_api_management/main.tf
The `connection_string` for the `azurerm_api_management_logger` resource has been introduced in version `4.1.0` of the provider
Fixes #CES-809
=> Upgrade APIM module minimum provider version

website/docs/infrastructure/appservice-hidden-appsettings.md
Fix broken link in "Ensuring Azure AppSettings Visibility in Terraform Plans" doc.
=> Update AppService documentation with KeyVault key rotation link

website/docs/conventions/pull-requests/acceptance-criteria.md, website/docs/conventions/pull-requests/auto-merge.md, website/docs/conventions/pull-requests/changeset.md, website/docs/conventions/pull-requests/format.md, website/docs/conventions/pull-requests/index.md, website/docs/guidelines/index.md
Consolidate pull request guidelines into a dedicated conventions section to enhance organization and accessibility for contributors.
=> Move Pull Request Guidelines under Convention section

.changeset/early-lizards-beg.md, website/docs/infrastructure/infrastructure-as-code/publishing-terraform-modules.md, website/docs/infrastructure/infrastructure-as-code/using-terraform-registry-modules.md
To guide into the publishing and usage of the terraform registry, two documentation pages had been published on the dx website.
Due to the change of GH organization (hence the terraform registry namespace) from pagopa to pagopa-dx, some corrections were needed.
Resolves #CES-805
Depends on #336
=> Edit terraform registry documentation after namespace change to pagopa-dx

yarn.lock
The yarn.lock file requires the entries to be placed in alphabetical order.
In the release of the azure_cdn module, after a merge conflict resolution, the yarn.lock got out of order.
=> Fix yarn lock entries order after azure_cdn release

.changeset/pretty-fishes-exercise.md, website/docs/conventions/pull-requests/format.md
Discourage the use of images and links in PR description in favor of a comment in the PR.
PR description will be the commit description of the merge commit.
=> Update PR description guideline

.github/copilot/code-instructions.md, .github/copilot/commit-instructions.md, .github/copilot/pull-request-instructions.md, .github/copilot/review-instructions.md, .github/copilot/test-instructions.md, .vscode/settings.json
Add Copilot guidelines for code generation, commit messages, pull requests, reviews, and tests.
Content is stubbed, consider these files as placeholders by now.
=> Add GitHub Copilot guidelines

.changeset/odd-coats-clap.md, apps/website/docs/infrastructure/appservice-hidden-appsettings.md, infra/modules/azure_function_app/locals.tf, infra/modules/azure_function_app/variables.tf
By using Terraform >= 1.10.x, the AppSettings property was marked as sensitive and therefore no longer displayed.
By forcing the boolean local to not being sensitive, the "mark" is not propagated to the `app_settings` resource property, which then doesn't result sensitive anymore
Closes CES-740
=> Fix an issue that prevented AppSettings to be displayed in Terraform Plans

.changeset/shaggy-spies-perform.md, infra/modules/azure_container_app_environment/README.md, infra/modules/azure_container_app_environment/container_app_environment.tf, infra/modules/azure_container_app_environment/tests/containerappenv.tftest.hcl, infra/modules/azure_container_app_environment/variables.tf
To reduce configuration complexity the variable `zone_redundant` now is defined automatically, based on environment in use:
if environment is `dev` zone redundancy is `true`, otherwise is `false`.
Resolves: CES-856
=> Removed zone_redundant variable into Container App Environment module

.github/workflows/push_modules_to_subrepo.yml
Fix the workflow when a PR is merged
=> Add current_ref value into push_modules_to_subrepo workflow

.changeset/tough-owls-live.md, infra/modules/azure_github_environment_bootstrap/README.md, infra/modules/azure_github_environment_bootstrap/container_app_job_runner.tf, infra/modules/azure_github_environment_bootstrap/data.tf, infra/modules/azure_github_environment_bootstrap/locals.tf, infra/modules/azure_github_environment_bootstrap/outputs.tf, infra/modules/azure_github_environment_bootstrap/variables.tf
Reuse `github_selfhosted_runner_on_container_app_jobs` module in `azure_github_environment_bootstrap`.
This also involves:
- the addition of a variables to control the job timeout
- the possibility to use KeyVaults with RBAC as access model
Closes CES-864
=> Reuse GitHub SelfHosted Runner on Container App Job module in Bootstrapper

.changeset/twelve-planes-repeat.md, infra/modules/azure_container_app/README.md, infra/modules/azure_container_app/container_app.tf, infra/modules/azure_container_app/tests/containerapp.tftest.hcl, infra/modules/azure_container_app/tests/setup/README.md, infra/modules/azure_container_app/tests/setup/main.tf, infra/modules/azure_container_app/variables.tf, infra/resources/dev/README.md, infra/resources/dev/data.tf, infra/resources/dev/locals.tf, infra/resources/dev/main.tf, infra/resources/dev/tfmodules.lock.json
Container App module now supports secrets.
Secrets are only supported by using KeyVault references, as best practices suggests. The Container App should have roles to read secrets from KV.
Closes CES-927
=> Add secret support to Container App module

.changeset/shaggy-lies-mate.md, infra/provider/internal/provider/function_resource_name.go
Update the provider to fix the handling of the domain parameter in the `resource_name` function. Previously, the domain parameter could not be explicitly defined; using an empty string (`""`) was allowed, but passing `null` would result in an error. With this update, the domain parameter now supports `null` values without causing errors.
Resolves: CES-934
=> Update provider with Null value support for domain parameter

.devcontainer/features/trivy/devcontainer-feature.json, .devcontainer/features/trivy/install.sh
Update `install.sh` script to be run in a non-interactive shell
=> Fix trivy feature install script

.changeset/six-eagles-lie.md, packages/eslint-config/package.json, yarn.lock
This removes the yarn warning '@pagopa/eslint-config@workspace:packages/eslint-config [db966] doesn't provide typescript (paf7fa), requested by typescript-eslint.' and prepare the package to be ready to the migration to the new major of typescript-eslint package.
=> Add typescript as dependency

.changeset/polite-seas-clean.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/README.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/locals.tf, infra/modules/github_selfhosted_runner_on_container_app_jobs/main.tf
This PR removes all instances of the naming_convention module from the GitHub Self Hosted module. The functionality has been replaced with the new naming convention function provided by the pagopa-dx/azure provider.
Resolves: CES-928
=> Remove `naming_convention` inside GitHub Self Hosted module in favor of `pagopa-dx/azure` provider function

.changeset/tiny-rules-drum.md, infra/modules/azure_cdn/README.md, infra/modules/azure_cdn/cdn.tf, infra/modules/azure_cdn/examples/basic/README.md, infra/modules/azure_cdn/examples/basic/locals.tf, infra/modules/azure_cdn/examples/basic/main.tf, infra/modules/azure_cdn/examples/basic/versions.tf, infra/modules/azure_cdn/locals.tf, infra/modules/azure_cdn/main.tf, infra/modules/azure_cdn/tests/setup/README.md, infra/modules/azure_cdn/tests/setup/main.tf
This PR removes all instances of the naming_convention module from the CDN module. The functionality has been replaced with the new naming convention function provided by the pagopa-dx/azure provider.
Resolves: CES-916
=> Remove `naming_convention` inside CDN module in favor of `pagopa-dx/azure` provider function

.changeset/clean-dancers-burn.md, infra/modules/azure_postgres_server/README.md, infra/modules/azure_postgres_server/example/complete/README.md, infra/modules/azure_postgres_server/example/complete/locals.tf, infra/modules/azure_postgres_server/example/complete/main.tf, infra/modules/azure_postgres_server/example/complete/versions.tf, infra/modules/azure_postgres_server/locals.tf, infra/modules/azure_postgres_server/main.tf, infra/modules/azure_postgres_server/network.tf, infra/modules/azure_postgres_server/replica.tf, infra/modules/azure_postgres_server/tests/setup/README.md, infra/modules/azure_postgres_server/tests/setup/main.tf
This PR removes all instances of the naming_convention module from the PostgreSQL module. The functionality has been replaced with the new naming convention function provided by the pagopa-dx/azure provider.
Resolves: CES-921
=> Remove `naming_convention` inside PostgreSQL module in favor of `pagopa-dx/azure` provider function

.changeset/light-cobras-clap.md, infra/modules/azure_function_app/README.md, infra/modules/azure_function_app/examples/complete/README.md, infra/modules/azure_function_app/examples/complete/locals.tf, infra/modules/azure_function_app/examples/complete/main.tf, infra/modules/azure_function_app/examples/complete/versions.tf, infra/modules/azure_function_app/locals.tf, infra/modules/azure_function_app/main.tf, infra/modules/azure_function_app/tests/setup/README.md, infra/modules/azure_function_app/tests/setup/main.tf, infra/modules/azure_function_app_exposed/README.md, infra/modules/azure_function_app_exposed/examples/complete/README.md, infra/modules/azure_function_app_exposed/examples/complete/locals.tf, infra/modules/azure_function_app_exposed/examples/complete/main.tf, infra/modules/azure_function_app_exposed/examples/complete/versions.tf, infra/modules/azure_function_app_exposed/locals.tf, infra/modules/azure_function_app_exposed/main.tf, infra/modules/azure_function_app_exposed/tests/setup/README.md, infra/modules/azure_function_app_exposed/tests/setup/main.tf
This PR removes all instances of the naming_convention module from the Function App and Function App Exposed modules. The functionality has been replaced with the new naming convention function provided by the `pagopa-dx/azure provider`.
Resolves: CES-915
=> Remove `naming_convention` inside Function App modules in favor of `pagopa-dx/azure` provider function

.changeset/sixty-foxes-fetch.md, infra/modules/azure_app_service/README.md, infra/modules/azure_app_service/app_service_plan.tf, infra/modules/azure_app_service/examples/complete/README.md, infra/modules/azure_app_service/examples/complete/locals.tf, infra/modules/azure_app_service/examples/complete/main.tf, infra/modules/azure_app_service/examples/complete/versions.tf, infra/modules/azure_app_service/locals.tf, infra/modules/azure_app_service/main.tf, infra/modules/azure_app_service/networking.tf, infra/modules/azure_app_service/subnets.tf, infra/modules/azure_app_service/tests/setup/README.md, infra/modules/azure_app_service/tests/setup/main.tf, infra/modules/azure_app_service_exposed/README.md, infra/modules/azure_app_service_exposed/app_service_plan.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_app_service_exposed/examples/complete/README.md, infra/modules/azure_app_service_exposed/examples/complete/locals.tf, infra/modules/azure_app_service_exposed/examples/complete/main.tf, infra/modules/azure_app_service_exposed/examples/complete/versions.tf, infra/modules/azure_app_service_exposed/locals.tf, infra/modules/azure_app_service_exposed/main.tf, infra/modules/azure_app_service_exposed/tests/setup/README.md, infra/modules/azure_app_service_exposed/tests/setup/main.tf
This PR removes all instances of the `naming_convention` module from the App Service and App Service Exposed modules. The functionality has been replaced with the new naming convention function provided by the `pagopa-dx/azure` provider.
Resolves: CES-914
=> Remove `naming_convention` inside App Service modules in favor of `pagopa-dx/azure` provider function

.changeset/polite-eels-train.md, infra/modules/azure_api_management/README.md, infra/modules/azure_api_management/example/complete/README.md, infra/modules/azure_api_management/example/complete/locals.tf, infra/modules/azure_api_management/example/complete/main.tf, infra/modules/azure_api_management/example/complete/versions.tf, infra/modules/azure_api_management/locals.tf, infra/modules/azure_api_management/main.tf, infra/modules/azure_api_management/network.tf, infra/modules/azure_api_management/tests/setup/README.md, infra/modules/azure_api_management/tests/setup/main.tf
This PR removes all instances of the naming_convention module from the APIM module. The functionality has been replaced with the new naming convention function provided by the pagopa-dx/azure provider.
Resolves: CES-920
=> Remove `naming_convention` inside APIM module in favor of `pagopa-dx/azure` provider function

.changeset/empty-dancers-sniff.md, infra/modules/azure_github_environment_bootstrap/README.md, infra/modules/azure_github_environment_bootstrap/locals.tf, infra/modules/azure_github_environment_bootstrap/main.tf
This PR removes all instances of the naming_convention module from the Azure github Bootstrap module. The functionality has been replaced with the new naming convention function provided by the pagopa-dx/azure provider.
Resolves: CES-929
=> Remove `naming_convention` inside bootstrap module in favor of `pagopa-dx/azure` provider function

.github/copilot/code-instructions.md
Introduce a guideline for utilizing Azure best practices when generating code or performing Azure-related operations with GitHub Copilot.
=> Add Azure best practices guideline for code generation

.changeset/lovely-falcons-remember.md, apps/website/docs/articles/azure-tracing.md
Gives some instruction to instrument a Next.js application deployed on an Azure App Service
Closes CES-880
=> Update Azure tracing article

.changeset/cute-masks-brush.md, packages/eslint-config/package.json, yarn.lock
The `eslint-config` package required an exact version of `eslint` instead of the previous major (`8.x`)
=> Fix peer dependency version

.changeset/hip-seas-beg.md, .changeset/khaki-taxis-happen.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service_exposed/app_service.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app_exposed/function_app.tf, infra/modules/azure_function_app_exposed/function_app_slot.tf, packages/azure-tracing/README.md, packages/azure-tracing/src/azure/monitor/env.ts, packages/azure-tracing/src/azure/monitor/index.ts, packages/azure-tracing/src/azure/monitor/start-from-env.ts
Decouple the `@pagopa/azure-tracing` package from the DX modules.
Fixes CES-967
=> Remove custom `APPINSIGHTS_CONNECTION_STRING` environment variable

.github/actions/azure-login/action.yaml, .github/actions/node-setup/action.yaml, .github/actions/slack-notification/action.yaml, .github/actions/terraform-setup/action.yaml, renovate.json
This PR introduces Renovate bot configuration to automate dependency management across the project. Key features:
- Sets up separate grouping for GitHub Actions updates
- Configures scheduled updates for Terraform providers and modules
- Schedules updates to run on Monday before 8AM
- Uses separate PR for major version updates
Resolves: CES-977 CES-978
=> Add Renovate configuration for automated dependency updates

.changeset/twelve-turtles-grin.md, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app/tests/functionapp.tftest.hcl, infra/modules/azure_function_app_exposed/function_app.tf, infra/modules/azure_function_app_exposed/function_app_slot.tf, infra/modules/azure_function_app_exposed/tests/functionapp.tftest.hcl
Upgrade minimum TLS version from 1.2 to 1.3 for Function Apps and Slots for policy alignment. 
This change affects both standard and exposed modules.
Resolves: CES-836
=> TLS 1.3 Upgrade for Azure Function Apps modules

.changeset/fast-olives-call.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service/tests/appservice.tftest.hcl, infra/modules/azure_app_service_exposed/app_service.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_app_service_exposed/tests/appservice.tftest.hcl
Upgrade minimum TLS version from 1.2 to 1.3 for App Services and Slots for policy alignment.
This change affects both standard and exposed modules.
Resolves: CES-982
=> TLS 1.3 Upgrade for Azure App Services modules

.changeset/open-dingos-prove.md, infra/modules/azure_core_infra/locals.tf
The simple addition of these dns zones makes public application insights unreachable.
=> Remove app insights private dns zones

.changeset/twelve-turtles-grin.md, infra/modules/azure_function_app/README.md, infra/modules/azure_function_app/examples/complete/README.md, infra/modules/azure_function_app/examples/complete/versions.tf, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app/main.tf, infra/modules/azure_function_app/tests/functionapp.tftest.hcl, infra/modules/azure_function_app/tests/setup/README.md, infra/modules/azure_function_app/tests/setup/main.tf, infra/modules/azure_function_app_exposed/README.md, infra/modules/azure_function_app_exposed/examples/complete/README.md, infra/modules/azure_function_app_exposed/examples/complete/versions.tf, infra/modules/azure_function_app_exposed/function_app.tf, infra/modules/azure_function_app_exposed/function_app_slot.tf, infra/modules/azure_function_app_exposed/main.tf, infra/modules/azure_function_app_exposed/tests/functionapp.tftest.hcl, infra/modules/azure_function_app_exposed/tests/setup/README.md, infra/modules/azure_function_app_exposed/tests/setup/main.tf
Upgrade minimum TLS version from 1.2 to 1.3 for Function Apps and Slots for policy alignment.
This change affects both standard and exposed modules.
Resolves: CES-836
=> TLS 1.3 Upgrade for Azure Function Apps modules Major

.changeset/fast-olives-call.md, infra/modules/azure_app_service/README.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service/examples/complete/README.md, infra/modules/azure_app_service/examples/complete/versions.tf, infra/modules/azure_app_service/main.tf, infra/modules/azure_app_service/tests/appservice.tftest.hcl, infra/modules/azure_app_service/tests/setup/README.md, infra/modules/azure_app_service/tests/setup/main.tf, infra/modules/azure_app_service_exposed/README.md, infra/modules/azure_app_service_exposed/app_service.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_app_service_exposed/examples/complete/README.md, infra/modules/azure_app_service_exposed/examples/complete/versions.tf, infra/modules/azure_app_service_exposed/main.tf, infra/modules/azure_app_service_exposed/tests/appservice.tftest.hcl, infra/modules/azure_app_service_exposed/tests/setup/README.md, infra/modules/azure_app_service_exposed/tests/setup/main.tf
Upgrade minimum TLS version from 1.2 to 1.3 for App Services and Slots for policy alignment.
This change affects both standard and exposed modules.
Resolves: CES-982
=> TLS 1.3 Upgrade for Azure App Services modules Major

.changeset/tame-yaks-shout.md, infra/modules/azure_api_management/network.tf
Add [recommended rules](https://learn.microsoft.com/en-us/azure/api-management/api-management-using-with-internal-vnet#configure-nsg-rules) to APIM's NSG.
Default settings put restrictions over components connectivity (e.g. inbounds are allowed only from VNET and load balancer), but the new rules restrict inbounds ports and the outbound services. 
Close CES-1017
=> add rules to nsg

.changeset/plain-bees-sit.md, infra/modules/azure_app_service/README.md, infra/modules/azure_app_service/app_service.tf, infra/modules/azure_app_service/app_service_slot.tf, infra/modules/azure_app_service/tests/appservice.tftest.hcl, infra/modules/azure_app_service/variables.tf, infra/modules/azure_app_service_exposed/README.md, infra/modules/azure_app_service_exposed/app_service.tf, infra/modules/azure_app_service_exposed/app_service_slot.tf, infra/modules/azure_app_service_exposed/tests/appservice.tftest.hcl, infra/modules/azure_app_service_exposed/variables.tf, infra/modules/azure_function_app/README.md, infra/modules/azure_function_app/function_app.tf, infra/modules/azure_function_app/function_app_slot.tf, infra/modules/azure_function_app/tests/functionapp.tftest.hcl, infra/modules/azure_function_app/variables.tf, infra/modules/azure_function_app_exposed/README.md, infra/modules/azure_function_app_exposed/function_app.tf, infra/modules/azure_function_app_exposed/function_app_slot.tf, infra/modules/azure_function_app_exposed/tests/functionapp.tftest.hcl, infra/modules/azure_function_app_exposed/variables.tf
This pull request reverts the TLS protocol version from 1.3 back to 1.2 for our App Service and Function App infrastructure modules. The change was necessary due to compatibility issues discovered with certain client applications that don't fully support TLS 1.3 yet.
Added new `tls_version` variable to allow flexible selection of TLS version.
Resolves: CES-1024
=> Revert TLS from 1.3 to 1.2 for App Service and Function App modules

.changeset/ready-goats-bathe.md, infra/modules/azure_service_bus_namespace/service_bus.tf
Match what [documentation suggests](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#public_network_access_enabled-2), even though no practical change was noticed
Close CES-1031
=> Set network access property to false for Service Bus Namespace

.github/workflows/infra_drift_detection.yml
This PR updates the `terraform plan` command within the drift detection workflow to include the `-lock=false` flag.
This change prevents the `plan` operation from attempting to acquire a lock on the Terraform state file. In scenarios where another Terraform operation (e.g., `apply`) might be holding the lock, the `plan` command would previously wait, potentially blocking the CI pipeline.
By adding `-lock=false`, the plan can proceed without locking, ensuring the drift detection workflow does not get stuck and cause pipeline delays or failures due to lock contention. This is a safe operation for a read-only command like `plan`.
Resolves: CES-1028
=> Prevent terraform plan from acquiring lock in drift detection

.changeset/great-tips-jump.md, .changeset/loud-dryers-travel.md, packages/azure-tracing/README.md, packages/azure-tracing/package.json, packages/azure-tracing/src/azure/functions/v3/index.ts, yarn.lock
To ensure the legacy Azure Function programming model, requests are traced, we need to wrap the handler function in an OpenTelemetry wrapper that manipulates the context to have correlated requests on Application Insights.
Closes CES-1016
=> Add support to Azure Function with programming model v3

.changeset/silly-coats-stick.md, apps/website/docs/getting-started/monorepository-setup.md, infra/modules/azure_github_environment_bootstrap/README.md
This PR updates documentation to clarify Azure RBAC permission requirements for the initial setup of the `azure-github-environment-bootstrap` module.
Resolves: CES-1020
=> Clarify Azure RBAC permissions for bootstrap module initial setup

apps/website/docs/infrastructure/azure/using-service-bus.md
Update documentation to specify the need for assigning the `Contributor` role to the Principal ID for managing the Service Bus Namespace. Include guidance on using the recommended module for role assignment and mention manual configuration options.
=> Clarify role assignment for managing Service Bus Namespace

.changeset/sharp-pants-read.md, infra/scripts/lock-modules.sh
Fix a bug causing inconsistent locking due to differences in the version of the `sort` command
Implement extensive logging in JSON format
Enhance lock files adding the module's version and name
Resolves CES-1055
=> Upgraded modules lock pre-commit script

.changeset/rotten-frogs-divide.md, infra/modules/azure_cdn/README.md, infra/modules/azure_cdn/cdn.tf, infra/modules/azure_cdn/examples/basic/README.md, infra/modules/azure_cdn/examples/basic/main.tf, infra/modules/azure_cdn/outputs.tf, infra/modules/azure_cdn/variables.tf
Added `rule_set_id` output that exposes the Front Door Rule Set ID. This allows users to implement custom rules via the `azurerm_cdn_frontdoor_rule` resource and link them to the rule set provided by the module.
Resolves CES-1062
=> Manage FrontDoor rule sets in Azure CDN module

.changeset/config.json
Doing this, also the Terraform module releases are going to be visible under the releases section on GitHub
=> Remove snapshot and add privatePackage options

.devcontainer/features/azure-functions-core-tools/devcontainer-feature.json, .devcontainer/features/azure-functions-core-tools/install.sh
TL;DR: Pin `azure-functions-core-tools` to version `4.0.7030`
[Microsoft is currently working on an official Linux ARM64 release (now in **Preview**)](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.7332-preview1), which will eventually be available via **NPM** or **APT**, eliminating the need to manually build the CLI from source. 
To support this platform, recent changes were made to the source code that are incompatible with the build steps used by this **devcontainer feature**.
As a result, we will now only support version `4.0.7030`, which is the latest version compatible with our `install.sh` script.
Once the official build is released, this feature will be **deprecated** and replaced by the [community-maintained …
=> Pin `azure-function-core-tools` version

.vscode/extensions.json, .vscode/settings.json, .yarn/sdks/eslint/bin/eslint.js, .yarn/sdks/eslint/lib/api.js, .yarn/sdks/eslint/lib/unsupported-api.js, .yarn/sdks/eslint/package.json, package.json, yarn.lock
This PR makes eslint extension for VSCode work with Yarn pnp.
=> Make ESLint VSCode extension work

.github/workflows/static_analysis.yaml
The static analysis github action was showing an empty table when modules locks had changed
=> Fix empty table in static analysis GH actions resume

.changeset/angry-buckets-camp.md, infra/modules/azure_role_assignments/modules/storage_account/locals.tf
Assign the new custom role "PagoPA Storage Queue Data Message Contributor" to storage queue "reader" role
=> Allow queue readers to set visibility timeout

package.json, pnpm-lock.yaml
Revert https://github.com/pagopa/dx/pull/731
With the previous change, I made the root package (`@pagopa/dx`) dependent on the CLI package (`@pagopa/dx-cli`), introducing a circular dependency since dx-cli was already dependent on the root package, as per the way pnpm packages works.
This change introduced an unintended (but predictable) side effect: each change on `@pagopa/dx-cli` triggered a change for all the workspaces in the monorepo.
I want to use `turbo` to build only the changed packages, using `turbo build --affected`
Example 1:
1. I make changes in `apps/website`.
2. I run `turbo build --affected`.
3. Turbo runs the `build` command against the affected target(s) and their dependents.
4. The target is `apps/website`, since it's the only package with changes and it has no …
=> Remove dx-cli from root

.changeset/beige-signs-exist.md, apps/cli/src/domain/__tests__/info.test.ts, apps/cli/src/domain/info.ts
The `info` command now shows, if configured, the Node version.
Closes CES-1152
=> Check Node version

.changeset/eleven-states-dig.md, .github/workflows/release-azure-staticapp-v1.yaml, .github/workflows/release-typescript-static-website-deploy-v1.yaml, apps/website/docs/pipelines/build-deploy-static-web-app.md
This PR introduces a new reusable GitHub Actions workflow to build and deploy static sites to **Azure Static Web Apps**. It standardizes our deployment process and adds support for automated Pull Request previews.
Resolves: CES-1180
=> Add GitHub Workflow for Static Web App build and deploy

.changeset/hip-emus-serve.md, infra/modules/azure_storage_account/storage_account.tf
Ignore customer_managed_key value as per [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account) to avoid removing CMK already instantiated created via the azurerm_storage_account_customer_managed_key resource
Resolves CES-1226
=> Ignore customer_managed_key value asking for changes although managed with external resource

.pre-commit-config.yaml, infra/core/dev/main.tf, infra/core/dev/tfmodules.lock.json
Trivy fails occasionally on first run in CI due to a missing cache folder. We now set the cache directory to a known path.
Resolves CES-1249
=> Fix trivy failing for missing cache folder

.changeset/neat-eggs-raise.md, packages/azure-tracing/package.json, pnpm-lock.yaml
This pull request updates the OpenTelemetry-related dependencies in the `@pagopa/azure-tracing` package to address a previous bug and allowing to remove a local patch.
Closes CES-1248
=> Update OpenTelemetry related dependencies

.changeset/swift-beers-appear.md, packages/monorepo-generator/templates/monorepo/.pre-commit-config.yaml
This pull request introduces a new `.pre-commit-config.yaml` file to the monorepo generator template, enabling projects scaffolded with the generator to have pre-commit hooks set up by default. This helps standardize and automate code quality checks, especially for Terraform code, across generated projects.
Closes CES-1256
=> Add pre-commit-config to monorepo template

.changeset/yellow-queens-fly.md, packages/monorepo-generator/src/index.ts, packages/monorepo-generator/templates/monorepo/turbo.json
This pull request adds support for generating a `turbo.json` configuration file when scaffolding a new monorepo. This change ensures that new monorepos are set up with sensible defaults for task orchestration using Turborepo.
Closes CES-1257 CES-1265
=> Scaffold turbo configuration

packages/monorepo-generator/src/index.ts
This pull request introduces a new prompt to the monorepo generator, allowing users to select a cloud provider when setting up a repository. This enhances the generator's flexibility by supporting both AWS and Azure options.
New feature:
* Added a cloud provider selection prompt (`csp`) to `getPrompts`, with choices for AWS and Azure, defaulting to Azure.
Closes CES-1280
=> Add CSP selection prompt

.changeset/nasty-pants-call.md, packages/monorepo-generator/package.json, packages/monorepo-generator/src/actions/pnpm.ts, packages/monorepo-generator/src/index.ts, pnpm-lock.yaml
This pull request introduces support for `pnpm` as the package manager in the monorepo generator, along with automatic configuration of the `pnpm-plugin-pagopa` plugin. The changes ensure that new monorepos are set up with `pnpm` and the relevant plugin out of the box.
Closes CES-1268
=> Enable and configure pnpm when scaffolding a new monorepo

apps/cli/src/adapters/commander/commands/init.ts, apps/cli/src/index.ts, packages/monorepo-generator/src/actions/terraform.ts
This pull request makes minor improvements by removing unnecessary ESLint disable comments for console usage across several files. The changes help clean up the codebase without affecting functionality.
=> Remove eslint-disable-next-line no-console comment

.changeset/angry-lands-hang.md, apps/website/docs/azure/static-websites/setting-up-azure-static-web-app.md, infra/resources/_modules/dx_website/README.md, infra/resources/_modules/dx_website/main.tf, infra/resources/_modules/testing/README.md, infra/resources/prod/tfmodules.lock.json
The former "free" sku size limited the number of preview environments to 3. This will increase them to 10.
=> Set standard tier to dx website

.changeset/evil-islands-hope.md, apps/cli/src/adapters/codemods/use-pnpm.ts
The previous regex replaced the wrong capture group generating invalid pnpm commands
=> Fix regex in `use-pnpm`

.changeset/upset-bears-look.md, infra/modules/github_selfhosted_runner_on_container_app_jobs/container_app_job.tf
=> Enable ETags property on self-hosted GitHub runner's autoscaler

infra/core/dev/README.md, infra/core/dev/dns.tf, infra/core/dev/tfmodules.lock.json, infra/core/prod/.terraform.lock.hcl, infra/core/prod/README.md, infra/core/prod/dns.tf, infra/core/prod/tfmodules.lock.json
Creates the dev.devex.pagopa.it dns zone to expose public PoC and applications
=> Create dev devex dns zone and allow AWS ACM certificates validation

.github/actions/build-workspace/action.yaml
the current filter installs only the `$WORKSPACE_NAME` direct dependencies, but we need to install also the indirect ones to make our projects buildable
=> Fix `pnpm install` filter

.github/workflows/release-azure-appsvc-v1.yaml
Breaking symlinks can cause problems at runtime because `node` is unable to reach certain indirect dependencies.
=> Preserve simlinks on pnpm artifact build
